query project($id: String!) {
    project(id: $id) {
        environments {
            edges {
                node {
                    id
                    name
                }
            }
        }
    }
}
