query project($id: String!) {
    project(id: $id) {
        environments {
            edges {
                node{
                    id
                    name
                    serviceInstances {
                        edges {
                            node {
                                serviceId
                                serviceName
                                service {
                                    icon
                                    projectId
                                }
                                createdAt
                                updatedAt
                                latestDeployment {
                                    id
                                    status
                                    meta
                                    instances {
                                        id
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
