mutation serviceUpdate($id: String!, $input: ServiceUpdateInput!) {
    serviceUpdate(id: $id, input: $input) {
        id
        name
        icon
        createdAt
        updatedAt
        projectId
    }
}
