query variables($projectId: String!, $environmentId: String!, $serviceId: String) {
    variables(
        projectId: $projectId
        environmentId: $environmentId
        serviceId: $serviceId
        unrendered: true
    )
}
